services:
  web:
    image: node:22-alpine
    working_dir: /srv/app
    ports:
      - "3000:3000"
    command:
      - sh
      - -lc
      - |
        set -e
        apk add --no-cache git ca-certificates libc6-compat wget
        update-ca-certificates

        # fresh checkout each run
        rm -rf /srv/app && mkdir -p /srv/app
        git clone --depth 1 -b master \
          https://github.com/TimSmafield/my-next-shadcn.git \
          /srv/app

        npm ci || npm i
        # Next.js dev server, listen on all interfaces
        npm run dev -- -p 3000 -H 0.0.0.0
    healthcheck:
      # heartbeat hits your Next.js route: /api/healthz
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/api/healthz"]
      interval: 10s
      timeout: 2s
      retries: 10
      start_period: 20s
    restart: unless-stopped
