services:
  web:
    image: node:22-alpine
    working_dir: /srv
    ports:
      - "3000:3000"
    command:
      - sh
      - -lc
      - |
        set -e
        apk add --no-cache git ca-certificates libc6-compat
        update-ca-certificates

        # absolute paths only; create target dir explicitly
        rm -rf /srv/app && mkdir -p /srv/app

        # hardcoded public repo + branch
        git clone --depth 1 -b master \
          https://github.com/TimSmafield/my-next-shadcn.git \
          /srv/app

        cd /srv/app
        npm install
        npm run dev -- -p 3000 -H 0.0.0.0
